cmd_/home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0/datapath/linux/skbuff-openvswitch.o := gcc -Wp,-MD,/home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0/datapath/linux/.skbuff-openvswitch.o.d  -nostdinc -isystem /usr/lib/x86_64-linux-gnu/gcc/x86_64-linux-gnu/4.5.2/include -I/home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0/include -I/home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0/datapath/linux/compat -I/home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0/datapath/linux/compat/include  -I/usr/src/linux-headers-2.6.38-13-generic/arch/x86/include -Iinclude  -include include/generated/autoconf.h -Iubuntu/include  -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -O2 -m64 -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -maccumulate-outgoing-args -fstack-protector -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -Wframe-larger-than=1024 -fno-omit-frame-pointer -fno-optimize-sibling-calls -pg -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO -DVERSION=\"1.4.0\" -I/home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0/datapath/linux/.. -I/home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0/datapath/linux/.. -DBUILDNR=\"\" -g -include /home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0/datapath/linux/kcompat.h  -DMODULE  -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(skbuff_openvswitch)"  -D"KBUILD_MODNAME=KBUILD_STR(openvswitch_mod)" -c -o /home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0/datapath/linux/.tmp_skbuff-openvswitch.o /home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0/datapath/linux/skbuff-openvswitch.c

source_/home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0/datapath/linux/skbuff-openvswitch.o := /home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0/datapath/linux/skbuff-openvswitch.c

deps_/home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0/datapath/linux/skbuff-openvswitch.o := \
  /home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0/datapath/linux/kcompat.h \

/home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0/datapath/linux/skbuff-openvswitch.o: $(deps_/home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0/datapath/linux/skbuff-openvswitch.o)

$(deps_/home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0/datapath/linux/skbuff-openvswitch.o):
