# -*- makefile -*-
export builddir = /home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0/datapath/linux
export srcdir = /home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0/datapath/linux
export top_srcdir = /home/rs2m/OpenStack_Essex/Tools/openvswitch-1.4.0
export VERSION = 1.4.0
export BUILDNR = 0

include $(srcdir)/../Modules.mk
include $(srcdir)/Modules.mk

EXTRA_CFLAGS := -DVERSION=\"$(VERSION)\"
EXTRA_CFLAGS += -I$(srcdir)/..
EXTRA_CFLAGS += -I$(builddir)/..
ifeq '$(BUILDNR)' '0'
EXTRA_CFLAGS += -DBUILDNR=\"\"
else
EXTRA_CFLAGS += -DBUILDNR=\"+build$(BUILDNR)\"
endif
EXTRA_CFLAGS += -g
EXTRA_CFLAGS += -include $(builddir)/kcompat.h

# These include directories have to go before -I$(KSRC)/include.
# NOSTDINC_FLAGS just happens to be a variable that goes in the
# right place, even though it's conceptually incorrect.
NOSTDINC_FLAGS += -I$(top_srcdir)/include -I$(srcdir)/compat -I$(srcdir)/compat/include

obj-m := $(patsubst %,%_mod.o,$(build_modules))

define module_template
$(1)_mod-y = $$(notdir $$(patsubst %.c,%.o,$($(1)_sources)))
endef

$(foreach module,$(build_modules),$(eval $(call module_template,$(module))))
