
# This file is automatically generated by setup.py, So don't edit it. :)
version_info = {
    'branch_nick': '(no',
    'revision_id': 'f460a99baee6e37b624c070527f70d4a868b6223',
    'revno': 1419
}
